version: '3.6'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    volumes:
    - ./logstash/pipeline:/logstash_dir
    command: logstash -f /logstash/pipeline/logstash.conf 
    depends_on:
      - elasticsearch
    ports:
    - '9601:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"    
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    ports:
    - '5601:5601'
    depends_on:
      - elasticsearch  
    networks:
      - elk
volumes: 
  elastic_data: {}

networks:
  elk: